### ISSUE TITLE
Videos will not automatically switch to the next one inside playlists.

### ISSUE THREAD

**Issue by definitelynotklip** [PoomSmart/YouTubeLegacy#1]
Videos inside either automatically-created mixes, or manually created playlists, will simply not switch to the next one when they end.
The next/previous video buttons on the UI also do not work (you can use them in the first video you played but not the rest).

Tested on iPhone 11, iOS 13.5, YouTube v17.40.5, YouTube Legacy 1.0.

**Comment by definitelynotklip** [comment]
@PoomSmart I beg you to look into this, I have seen you hard at work fixing the other issues with the tweak. This is an incredibly important feature to me, I use YouTube to listen to music while I drive to and from work and currently have to manually switch songs every few minutes taking my eyes off the road. I also have to manually switch songs as I work, sometimes I use gloves or wear PPE or get dirty/wet and it's just not possible to do. Is there any workaround for this?

**Comment by PoomSmart** [comment]
Can't reproduce all those issues yet. Will update here if I found anything.

**Comment by definitelynotklip** [comment]
> Can't reproduce all those issues yet. Will update here if I found anything.

This happens using YouTube v17.40.5, tweak version v1.4.2, on an iPhone 11 using iOS 13.5, jailbroken with unc0ver 5.0.1. I only have the prerequisites for YouTube Legacy installed as far as YouTube is concerned; if you need my full tweak list let me know.

The issue: If I go into any of my playlists and tap on any song, it will play regularly until it ends; once it ends it will switch to the next song, with or without shuffle. After _that_ song also ends, songs will not automatically switch inside playlists anymore, the video will end as if Autoplay was not on. I can repeat the song with the repeat button normally. Clicking on the 'Next' (⏭) or 'Previous' (⏮) buttons does nothing. The process can be repeated by closing the song from the miniplayer and starting another.

My main issue is not the buttons not working per se, but rather the song not switching automatically once it ends. If one issue can be resolved without the other, I would prefer it if songs just switched on their own (for example with background play).

Demonstration:

https://github.com/user-attachments/assets/2ebd6b7f-1487-45af-90b3-0592a2ff6e15

If i can help you with any other info or test for you please let me know, this issue is killing me.

**Comment by PoomSmart** [comment]
This should be fixed in v1.5.6

**Comment by definitelynotklip** [comment]
@PoomSmart The issue isn't resolved, please keep looking into this! I have attached a video showing that I indeed have the latest version of YouTube Legacy (v1.5.8 as of writing this) along with its dependencies, and the previous/next buttons are still not working, neither does autoplay. I am still using YouTube v17.40.5 on the same iOS and hardware as described in the previous posts.

https://github.com/user-attachments/assets/13040ad0-6d26-4bec-ac26-0c39c3202334

**Comment by PoomSmart** [comment]
@definitelynotklip There was a regression. Upgrade to v1.5.9

**Comment by definitelynotklip** [comment]
> [@definitelynotklip](https://github.com/definitelynotklip) There was a regression. Upgrade to v1.5.9

Just updated, currently using v1.5.12. Autoplay and UI buttons are now fully functional again. Thanks!

**Comment by D1NK096** [comment]
I experienced the same issue on an iPad Mini 2 on iOS 12.5.7, Youtube v17.39.4, with the difference that the autoplay feature works
