### ISSUE TITLE
Wrong video is played sometimes from a channel page

### ISSUE THREAD

**Issue by dokisof** [PoomSmart/YouTubeLegacy#34]
iPad mini 2, YouTube 17.39.4, YouTube Legacy 1.8.1

1. Go to channel https://www.youtube.com/@WIRED/videos
2. Sort by views
3. Play video about Rubic's cube
4. Previous video is opened instead (about doctor)

![Image](https://github.com/user-attachments/assets/5297fac8-f321-4797-b21f-6e3134a20d0d)

If I change orientation to vertical (2 videos per row), it plays correctly

**Comment by PoomSmart** [comment]
Fixed in 1.8.2

**Comment by dokisof** [comment]
> Fixed in 1.8.2

Still does not work on the latest version. Almost impossible to select a specific video. It's either the first video from the same row or the last one from the previous row.

**Comment by dokisof** [comment]
@PoomSmart 

https://github.com/user-attachments/assets/6dcb1697-8722-4cc7-be70-e3caf0de2ab7
